### ISSUE TITLE
Docker Link of glacier simulator is not working

### ISSUE THREAD

**Issue by pat-schmitt** [OGGM/oggm-edu#175]
Hi @TimoRoth,

the docker link of the glacier simulator is not working and maybe you can help.

You changed the docker links here https://github.com/OGGM/oggm-edu/commit/b36de29b4ea0c609c22fba367e771832c511f1af and explained on slack that the ports I was using for the simulator were not best practice (as 0.0.0.0 just means 'any IP'). I just checked again and with `docker run -e BOKEH_ALLOW_WS_ORIGIN=127.0.0.1 -p 8085:8080 oggm/bokeh:20210130 git+https://github.com/OGGM/glacier_simulator.git@stable app.ipynb` and accessing with `http://127.0.0.1:8085/app` the app is not starting.

However the bad practice example with `docker run -e BOKEH_ALLOW_WS_ORIGIN=0.0.0.0:8080 -p 8080:8080 oggm/bokeh:20210130 git+https://github.com/OGGM/glacier_simulator.git@stable app.ipynb` and accessing with `http://0.0.0.0:8080/app` is working.

Is it only a problem on my side? (I just reinstalled and updated docker)
Do you have an idea what can cause the problem?

**Comment by TimoRoth** [comment]
Accessing via "http://0.0.0.0:8080/app" straight up cannot work, since 0.0.0.0 is not a valid IP address to connect to.
Listening on it only means to allow connections from anywhere.
It for that reason also does not work in the ALLOW_WS_ORIGIN field, since the origin will never be 0.0.0.0, but always 127.0.0.1, localhost, your machines actual address, or something like that.

I just tested the exact command for the glacier_simulator from the docs:
`docker run -e BOKEH_ALLOW_WS_ORIGIN=127.0.0.1 -p 8085:8080 oggm/bokeh:20210130 git+https://github.com/OGGM/glacier_simulator.git@stable app.ipynb` and it works absolutely fine for me.
The link it prints is obviously wrong and can't ever work, given it contains 0.0.0.0, which internally in the container is the correct address to listen on.

After I ran that command, I could reach the application on `http://127.0.0.1:8085`.
Same for the other two in the docs. They all work as expected for me.

**Comment by TimoRoth** [comment]
I can't really think of a reason why it would not work. It's pretty universal.
And something must be very wrong, or your Browser implicitly replaces it with localhost, if you can connect to 0.0.0.0.
Connecting to that address makes no logical sense, since it's not an address anything can have. It's just the "any address" value when opening a listening socket. Which means to listen on every available address of that host.

The address/hostname in BOKEH_ALLOW_WS_ORIGIN has to match the one in the Browsers address field. It's just a security measure browsers mandate.
The app will always listen on 0.0.0.0, port 8080, in the container. And docker then translates that to a different Port on the host. Like for example 8085.


I just noticed that for the glacier_simulator app specifically the link in the docs only got a partial update.
The link target didn't get the correct port. Maybe that's what was tripping you up?

**Comment by pat-schmitt** [comment]
Yes, the wrong link was the problem, as I just clicked on it on the website. Now it is working fine.

Thank you!

**Comment by fmaussion** [comment]
Can you send a fix to the website?

**Comment by pat-schmitt** [comment]
It is already fixed on the website, at least for me
